#!/usr/bin/ruby

use_frameworks!
platform :ios, "9.3"

target 'RendererExample' do
  pod 'Contentful'
  pod 'ContentfulRichTextRenderer', :path => '../'
  
  target 'RendererExampleTests' do
    inherit! :search_paths
    pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'master'
  end
end

