#!/usr/bin/ruby

use_frameworks!
platform :ios, "10.0"

target 'RendererExample' do
  pod 'Contentful'
  pod 'ContentfulRichTextRenderer', :path => '../'
  
  target 'RendererExampleTests' do
    inherit! :search_paths
    pod 'KIF'
    pod 'SnapshotTesting', :git => 'https://github.com/pointfreeco/swift-snapshot-testing.git'
  end
end

